server:
  port: 8092
spring:
  application:
    name: u-center
  #配置bus
  rabbitmq:
    host: bus.ping.sam.com
    port: 5672
    username: admin
    password: admin
#===========================================
  datasource:
    name: mytest
    url: jdbc:mysql://db.ping.sam.com:3306/mytest
    username: root
    password: admin
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，没有配置的情况下打开会直接报错，找不到实例
#    filters: stat
# 连接池的配置信息
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20





